---
sudo: false
language: ruby
cache: bundler
script: "bin/travis_check.sh"
matrix:
  fast_finish: true
  include:
  - rvm: 2.3.1
    dist: trusty
    env: PUPPET_INSTALL_TYPE=agent BEAKER_debug=true BEAKER_set=docker/ubuntu-14.04
    script: bundle exec rake beaker
    services: docker
    sudo: required
  - rvm: 2.3.1
    dist: trusty
    env: PUPPET_INSTALL_TYPE=agent BEAKER_debug=true BEAKER_set=docker/centos-7
    script: bundle exec rake beaker
    services: docker
    sudo: required
  - rvm: 2.3.1
    bundler_args: --without system_tests
    env: PUPPET_GEM_VERSION="~> 4.0" STDLIB_LOG_DEPRECATIONS="false"
  - rvm: 2.1.9
    bundler_args: --without system_tests
    env: PUPPET_GEM_VERSION="~> 4.0" STDLIB_LOG_DEPRECATIONS="false"
  - rvm: 2.1.5
    bundler_args: --without system_tests
    env: PUPPET_GEM_VERSION="~> 3.0" FUTURE_PARSER="yes"
  - rvm: 2.1.5
    bundler_args: --without system_tests
    env: PUPPET_GEM_VERSION="~> 3.0"
  - rvm: 1.9.3
    bundler_args: --without system_tests
    env: PUPPET_GEM_VERSION="~> 3.0"
notifications:
  email:
    - al@example42.com
