---
# Default settings for all vms (they can be overridden on each node)
vm:
  memory: 1024                 # MB or RAM to assign
  cpu: 1                       # Number of vCPU to assign to the VM
  box: centos7                 # Box used for the VM, from the box list in vagrant/boxes.yaml
  puppet_apply: false          # Run puppet apply on the local control-repo during provisioning
  puppet_agent: true           # Run puppet agent during provisioning
  facter_external_facts: false # Create external facts in facts.d/$fact.txt. Note 1
  facter_trusted_facts: true   # Create csr_attributes.yaml. Note 1
  synced_folder_type: vboxfs   # Sync folders types: nfs, vboxfs

# Note 1: Some facts are used in default hiera.yaml and needed for
# nodes classification. So it's better to set them, once.
# If you enable both external and trusted facts and keep the
# default manifests/site.pp you'll have a variable declaration error

# A local network is created among the VM. Here is configured.
network:
  range: 10.42.47.0/24   # Network address and mask to use
  ip_start_offset: 101   # Starting ip in the network for automatic assignement
  domain: demo           # Name of DNS domain for the created machines

# Puppet related settings
puppet:
  version: latest             # Version to use for OSS
  install_oss: false          # If to install Puppet OSS agent on the VMS
  install_pe: true            # If to install Puppet Enterprise agent on the VMS
  env: demo                   # Setting for the env fact (may be used in hiera.yaml)
  zone: demo                  # Setting for the zone fact (may be used in hiera.yaml)
  datacenter: vagrant         # Setting for the datacenter fact (may be used in hiera.yaml)
  application: default        # Setting for the application fact (may be used in hiera.yaml)
  master_vm:  puppet.demo     # Name of the VM which play as Puppet server for the others
  master_fqdn: 'puppet.demo'  # FQDN of the Puppet server to use with puppet agent
  link_controlrepo: false     # Add a link for a Puppet environment to the development control-repo
  environment: production           # Puppet environment to link to local control-repo and to use when Vagrant provisioning
  r10k_install: true                # If to run r10k on Puppet server to deploy controlrepo
  controlrepo: https://github.com/example42/psick.git  #Â URL of the controlrepo to deploy via r10k on Puppet Server

# Puppet Enterprise settings
  pe_version: '2019.5.0'         # Version of PE to install on the puppet server. See Note 2
  pe_download_root: 'https://s3.amazonaws.com/pe-builds/released/2019.5.0' # Download base url. See Note 2
  pe_verbose: true               # If to show PE installation output
  pe_relocate_manifests: false   # If to relocate manifests and module dir. Not needed in this setup.

#  Note 2: when changing the version, change also the download_root unless you have a
#  custom one. For locally downloaded files, for example, you can place something like:
#  pe_download_root: 'file:///Users/al/Downloads'

# Vagrant settings
vagrant:
  # Update host's /etc/hosts if you have the hostmanager plugin.
  # Needed for automatic decommissioning of nodes. If false, you've to manage
  # manually ssl certs removal of reinstalled nodes.
  hostmanager.manage_host: true # If true and you have the hostmanager plugin

# List of nodes shown in vagrant status
# Node names are based on the defined role. Here can be overridden vm defaults,
# it can be enforced a defined host name, added alieses, port forwarding and pe_role
nodes:
  - role: puppet
    pe_role: master
    memory: 6192
    cpu: 2
    aliases:
      - puppet
    forwarded_port:
      guest: 443
      host: 1743
    puppet_apply: false
  - role: puppetre
    memory: 4096
    cpu: 2
    puppet_apply: true
  - role: git
    memory: 2048
    forwarded_port:
      guest: 443
      host: 1744
    puppet_agent: false
  - role: cirunner
    count: 1
  - role: build
    count: 1
  - role: docker
    count: 1
    box: ubuntu1404
  - role: ostest
    hostname_base: pe-centos7
    count: 1
    box: centos7
  - role: ostest
    hostname_base: pe-centos6
    count: 1
    box: centos6
  - role: ostest
    hostname_base: pe-ubuntu1604
    count: 1
    box: ubuntu1604
  - role: ostest
    hostname_base: pe-suse12
    count: 1
    box: suse12
  - role: ostest
    hostname_base: pe-suse11
    count: 1
    box: suse11
