---
# Default settings for vms
vm:
  memory: 1024
  cpu: 1
  box: centos7 # From boxes list below
  puppet_apply: true
  puppet_agent: false

network:
  range: 10.42.41.0/24
  ip_start_offset: 101
  domain: ci.psick.io

puppet:
  version: latest
  env: dev
  zone: local
  master_ip: 10.42.44.10
#  master_hostname: dev-local-puppet-01

# Nodes shown in vagrant status 
nodes:
  - role: git
    count: 1
    memory: 2048
  - role: ci
    count: 1
    memory: 2048
  - role: compilemaster
    count: 1
    memory: 2048
  - role: puppet_db
    hostname_base: puppet-db
    count: 1
  - role: puppet_mom
    hostname_base: puppet-mom
    count: 1
    memory: 4096
    ip_address: 10.42.42.10
    puppet_apply: true
    aliases:
      - puppet

boxes:
  centos7:
    box: puppetlabs/centos-7.2-64-puppet
    breed: puppetlabs-centos7
  centos7_pe:
    box: puppetlabs/centos-7.0-64-puppet-enterprise
    breed: puppetlabs
  centos6:
    box: puppetlabs/centos-6.6-64-puppet
    breed: puppetlabs
  ubuntu1604:
    box: puppetlabs/ubuntu-16.04-64-puppet
    breed: puppetlabs-apt
  ubuntu1404:
    box: puppetlabs/ubuntu-14.04-64-puppet
    breed: puppetlabs-apt
  debian8:
    box: puppetlabs/debian-8.2-64-puppet
    breed: puppetlabs-apt

